services:
  elite-postgres:
    image: postgres:18.0
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - elite-postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    env_file: .env
    networks:
      - elite-network

  elite-spring:
    build: .
    container_name: elite_spring
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      elite-postgres:
        condition: service_healthy
    networks:
      - elite-network
    env_file: .env

volumes:
  elite-postgres_data:

networks:
  elite-network:
    driver: bridge